name: handy_window
description: |
  This package enhances the looks of Flutter applications on Linux by providing
  modern-looking Handy windows with rounded bottom corners.
homepage: https://github.com/ubuntu-flutter-community/handy_window
repository: https://github.com/ubuntu-flutter-community/handy_window
issue_tracker: https://github.com/ubuntu-flutter-community/handy_window/issues
version: 0.1.9

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/handy-window.css
    - assets/handy-window-dark.css
  plugin:
    platforms:
      linux:
        pluginClass: HandyWindowPlugin

platforms:
  linux:
